---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-mitragaurav10-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 2Gi
